# * --------------------------------  Information
name: todo_app
description: "A new Flutter project."
publish_to: 'none'

# * --------------------------------  version
version: 1.0.0+1

# * --------------------------------  environment
environment:
  sdk: '>=3.3.4 <4.0.0'

# * --------------------------------  dependencies
dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^8.1.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  draggable_expandable_fab: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  tutorial_coach_mark: ^1.2.11

# * --------------------------------  dev_dependencies
dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# * --------------------------------  flutter_gen
flutter_gen:
  output: lib/core/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true
    # rive: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto_sans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_sans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans/NotoSans-Black.ttf
          weight: 900
